:toc: macro
:toclevels: 5
:figure-caption!:

= Runcom

Runcom is a link:https://en.wikipedia.org/wiki/Run_commands[Run Command] portmanteau (i.e. `run +
[com]mand = runcom`) which provides common functionality for Command Line Interfaces (CLIs) in which
to manage global, local, or multiple caches, configurations, or data in general. It does this by
leveraging the https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html[XDG Base
Directory Specification] built atop the link:https://alchemists.io/projects/xdg[XDG]
implementation. In other words, Runcom is an advanced version of XDG.

toc::[]

== Features

* Wraps the link:https://alchemists.io/projects/xdg[XDG] implementation which provides access to
  the following environment variables:
** `$XDG_CACHE_HOME`
** `$XDG_CONFIG_HOME`
** `$XDG_CONFIG_DIRS`
** `$XDG_DATA_HOME`
** `$XDG_DATA_DIRS`
** `$XDG_STATE_HOME`
* Enhances the XDG cache, config, data, and state implementation. For the config, the following is
  supported:
** Supports loading of CLI-specific http://yaml.org[YAML] configuration file.
** Supports loading and merging of nested/complex configurations.
** Supports hash representation of configuration.

== Requirements

. https://www.ruby-lang.org[Ruby]

== Setup

To install, run:

[source,bash]
----
gem install runcom
----

Add the following to your Gemfile:

[source,ruby]
----
gem "runcom"
----

== Usage

The following describes the enhancements built atop the
link:https://alchemists.io/projects/xdg[XDG] implementation.

=== Overview

While there isn’t an environment convenience object as found in the `+XDG+` namespace, you can
instantiate each object individually:

[source,ruby]
----
cache = Runcom::Cache.new "example/data.json"
config = Runcom::Config.new "example/configuration.yml"
data = Runcom::Data.new "example/store.dat"
state = Runcom::State.new "example/history.log"
----

Each of the above objects share the same API:

* `#relative` - Answers the relative path from which the object was constructed.
* `#namespace` - Answers the relative namespace as a pathname object from which the object was
  constructed. The namespace must be identical across the cache, config, and data objects as this is
  what uniquely identifies and organizes all files associated with your program.
* `#file_name` - Answers the file name from which the object was constructed.
* `#current` - Answers first _existing_ file system path computed by `$XDG_*_HOME` followed by each
  computed `$XDG_*_DIRS` path in order defined. Otherwise, `nil` is answered back.
* `#all` - Answers all file system paths which is the combined `$XDG_*_HOME` and
  `$XDG_*_DIRS` values in order defined. These paths _may_ or _may not_ exist on the file system.
* `#inspect` - Answers a string representation of default XDG home and directory paths for debugging
  purposes.

Using the `cache` object (created above) as an example, here is what each method answers back:

[source,ruby]
----
cache.relative # => #<Pathname:example/data.json>
cache.namespace # #<Pathname:example>
cache.file_name # #<Pathname:data.json>
cache.current # #<Pathname:/Users/bkuhlmann/.cache/example/data.json>
cache.all # [#<Pathname:/Users/bkuhlmann/.cache/example/data.json>]
cache.inspect # "XDG_CACHE_HOME=/Users/bkuhlmann/.cache"
----

=== Variable Priority

Path precedence is determined in the following order (with the first taking highest priority):

. *Local Configuration* - If a `$XDG_*_HOME` or `$XDG_*_DIRS` path relative to the
  current working directory is detected, it will take precedence over the global configuration.
  This is the same behavior as found in Git where the local `.git/config` takes precedence over the
  global `$HOME/.gitconfig`.
. *Global Configuration* - When a local configuration isn’t found, the global configuration is used
  as defined by the _XDG Base Directory Specification_.

=== Configuration Specialization

The `Runcom::Config` deserves additional highlighting as it provides support for loading custom
CLI configurations directly from the command line or from custom locations. It is meant to be used
within your program(s).

An object is initialized as follows:

[source,ruby]
----
configuration = Runcom::Config.new "example/configuration.yml"
----

Default settings can be initialized as well:

[source,ruby]
----
configuration = Runcom::Config.new "example/configuration.yml", defaults: {name: "Example"}
----

Once a configuration has been initialized, a hash representation can be obtained:

[source,ruby]
----
configuration.to_h
----

A configuration can be merged with another hash (handy for runtime overrides):

[source,ruby]
----
updated_configuration = configuration.merge {name: "Updated Name"}
----

A configuration can also be merged with another configuration:

[source,ruby]
----
updated_configuration = configuration.merge Runcom::Config.new("other", defaults: {a: 1})
----

The current path of the configuration can be asked for as well:

[source,ruby]
----
configuration.current # "~/.config/example/configuration.yml"
----

For further details, study the public interface as provided by the
link:lib/runcom/config.rb[`Runcom::Config`] object.

=== Examples

Examples of gems built atop this gem are:

* link:https://alchemists.io/projects/rubysmith[Rubysmith] - A command line interface for
  smithing Ruby projects.
* link:https://alchemists.io/projects/gemsmith[Gemsmith] - A command line interface for smithing
  new Ruby gems.
* link:https://alchemists.io/projects/git-lint[Git Lint] - Enforces consistent Git commits.
* link:https://alchemists.io/projects/milestoner[Milestoner] - A command line interface for
  releasing Git repository milestones.
* link:https://alchemists.io/projects/pennyworth[Pennyworth] - A command line interface that
  enhances and extends link:https://www.alfredapp.com[Alfred] with Ruby support.
* link:https://alchemists.io/projects/pragmater[Pragmater] - A command line interface for
  managing/formatting source file pragma comments.
* link:https://alchemists.io/projects/sublime_text_kit[Sublime Text Kit] - A command line
  interface for managing Sublime Text metadata.
* link:https://alchemists.io/projects/tocer[Tocer] - A command line interface for generating
  table of contents for Markdown files.

== Development

To contribute, run:

[source,bash]
----
git clone https://github.com/bkuhlmann/runcom
cd runcom
bin/setup
----

You can also use the IRB console for direct access to all objects:

[source,bash]
----
bin/console
----

== Tests

To test, run:

[source,bash]
----
bin/rake
----

== link:https://alchemists.io/policies/license[License]

== link:https://alchemists.io/policies/security[Security]

== link:https://alchemists.io/policies/code_of_conduct[Code of Conduct]

== link:https://alchemists.io/policies/contributions[Contributions]

== link:https://alchemists.io/projects/runcom/versions[Versions]

== link:https://alchemists.io/community[Community]

== Credits

* Built with link:https://alchemists.io/projects/gemsmith[Gemsmith].
* Engineered by link:https://alchemists.io/team/brooke_kuhlmann[Brooke Kuhlmann].
