# frozen_string_literal: true

require "runcom/identity"
require "runcom/errors/base"
require "runcom/errors/syntax"
require "runcom/pair"
require "runcom/paths/standard"
require "runcom/paths/friendly"
require "runcom/paths/directory"
require "runcom/paths/combined"
require "runcom/xdg/configuration"
require "runcom/xdg/data"
require "runcom/xdg/cache"
require "runcom/xdg/environment"
require "runcom/configuration"
